version: "3.9"

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 10s
      retries: 5

  postgres_query:
    image: postgres:16
    container_name: postgres_query
    environment:
      - POSTGRES_USER=query
      - POSTGRES_PASSWORD=query
      - POSTGRES_DB=query_db
    ports:
      - "5434:5432"
    volumes:
      - query_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U query -d query_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  race_application_command_service:
    build:
      context: ./services/race-application-command-service
    container_name: race_application_command_service
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USERNAME=guest
      - RABBITMQ_PASSWORD=guest
    depends_on:
      - rabbitmq
    ports:
      - "8081:8080"

  race_application_query_service:
    build:
      context: ./services/race-application-query-service
    container_name: race_application_query_service
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USERNAME=guest
      - RABBITMQ_PASSWORD=guest
      - DB_HOST=postgres_query
      - DB_PORT=5432
      - DB_NAME=query_db
      - DB_USERNAME=query
      - DB_PASSWORD=query
      - JWT_SECRET=dev-shared-secret-please-change-this-is-a-very-long-secret-key-for-jwt-signing-that-is-at-least-256-bits-long
    depends_on:
      postgres_query:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    ports:
      - "8082:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  client:
    build:
      context: ./client
    container_name: race_application_client
    environment:
      - VITE_API_QUERY_URL=http://localhost:8082
      - VITE_API_COMMAND_URL=http://localhost:8081
    depends_on:
      race_application_query_service:
        condition: service_healthy
      race_application_command_service:
        condition: service_started
    ports:
      - "5173:80"

volumes:
  query_db_data: 