server:
  port: 8080
spring:
  application:
    name: race-application-query-service
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5434}/${DB_NAME:query_db}
    username: ${DB_USERNAME:query}
    password: ${DB_PASSWORD:query}
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        jdbc.lob.non_contextual_creation: true
  flyway:
    enabled: false
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}
app:
  rabbit:
    exchange: events.exchange
    routing:
      race: race.events
      application: application.events
    queues:
      races: query.races
      applications: query.applications
management:
  endpoints:
    web:
      exposure:
        include: health,info



